name: Uploady Release

on:
    workflow_dispatch:
        branches:
            - "release-**"
        inputs:
            version:
                type: choice
                description: Which version to release?
                required: false
                default: "patch"
                options:
                    - "patch"
                    - "minor"
                    - "major"
                    - "prepatch"
                    - "preminor"
                    - "premajor"
                    - "prerelease"

            preid:
                type: choice
                description: Which pre-release ID to use?
                required: false
                default: ""
                options:
                    - ""
                    - "rc"
                    - "alpha"
            mergeMaster:
                type: boolean
                description: Merge latest master?
                required: true
                default: true

permissions:
    #    id-token: write
    contents: write

defaults:
    run:
        shell: bash
        #working-directory:

jobs:
    release:
        name: Release Uploady
        environment: "Release"
        runs-on: ubuntu-latest
        steps:
            -   name: Check is Pre Release
                id: is-pre
                if: ${{ inputs.version == 'premajor' || inputs.version == 'preminor' || inputs.version == 'prepatch' || inputs.version == 'prerelease' }}
                run: |
                    echo "PRE_RELEASE=true" >> $GITHUB_OUTPUT

            -   name: Validate version with pre-id
                if: ${{ steps.is-pre.outputs.PRE_RELEASE == 'true' && inputs.preid == '' }}
                run: |
                    echo "🔴 Failing Job - Cant use version: (premajor, preminor, prepatch, prerelease) without selecting PreId too! >> $GITHUB_STEP_SUMMARY
                    exit 1

            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Define GIT Author
                run: |
                    git config user.email "ci@react-uploady.org"
                    git config user.name "Uploady CI"

            -   name: Merge Latest Master
                if: ${{ inputs.mergeMaster == true }}
                run: |
                    git merge origin/master -m "chore: merge content from master"

            -   uses: actions/setup-node@v3
                with:
                    node-version: "16.17"
                    cache: "yarn"

            -   name: Install Deps
                run: yarn --frozen-lockfile

            -   name: Clean
                run: yarn clean

            -   name: Define Lerna Args
                id: lerna-args
                run: |
                    if [ '${{ steps.is-pre.outputs.PRE_RELEASE }}' = 'true' ]
                    then
                        if [ '${{ inputs.preid }}' = 'rc' ]
                        then
                          echo "using args for RC release"
                          echo "VERSION=${{ inputs.version }} --preid rc" >> $GITHUB_OUTPUT
                          echo "PUBLISH=--dist-tag next" >> $GITHUB_OUTPUT
                        elif [ '${{ inputs.preid }}' = 'alpha' ]
                        then
                          echo "using args for Alpha release"
                          echo "VERSION=${{ inputs.version }}" >> $GITHUB_OUTPUT
                          echo "PUBLISH=--dist-tag alpha" >> $GITHUB_OUTPUT
                        fi
                    else
                      echo "using args for ${{ inputs.version }} release"
                      echo "VERSION=${{ inputs.version }}" >> $GITHUB_OUTPUT
                    fi

            -   name: Create Version
                id: version
                run: |
                    echo "### Using version args: ${{ steps.lerna-args.outputs.VERSION }}" >> $GITHUB_STEP_SUMMARY
                    lerna version ${{ steps.lerna-args.outputs.VERSION }} --force-publish=* --no-push --no-git-tag-version --yes

            -   name: Build Source
                run: yarn build

            -   name: Bundle Source
                run: yarn bundle:prod

            -   name: Authenticate with NPM Registry
                run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
                env:
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            -   name: Extract Version Changelog
                id: version-log
                uses: ./.github/actions/versionLog

            -   name: Create Version Name
                id: version-name
                run: |
                    echo "NEW_VERSION=${{ format('v{0}', steps.version-log.outputs.VERSION) }}" >> $GITHUB_OUTPUT

            -   name: Publish
                id: publish
                run: |
                    lerna publish from-package ${{ steps.lerna-args.outputs.PUBLISH }} --no-push --yes
                    echo "## Published: ${{ steps.version-name.outputs.NEW_VERSION }} :rocket:" >> $GITHUB_STEP_SUMMARY
                    echo "${{ steps.version-log.outputs.VERSION_LOG }}" >> $GITHUB_STEP_SUMMARY

            -   name: Push changes
                if: ${{ always() && steps.version.outcome == 'success' && steps.publish.outcome == 'success' }}
                run: |
                    git push
                    git tag -a ${{ steps.version-name.outputs.NEW_VERSION }} -m "tag for version: ${{ steps.version-name.outputs.NEW_VERSION }}"
                    git push origin ${{ steps.version-name.outputs.NEW_VERSION }}

            -   name: Create GH Release
                uses: ncipollo/release-action@v1
                with:
                    name: ${{ steps.version-name.outputs.NEW_VERSION }}
                    body: ${{ steps.version-log.outputs.VERSION_LOG }}
                    #draft: true
                    prerelease: ${{ fromJSON(steps.is-pre.outputs.PRE_RELEASE) }}
                    tag: ${{ steps.version-name.outputs.NEW_VERSION }}

            -   name: Create PR for Release
                id: pr
                uses: peter-evans/create-pull-request@v5
                with:
                    title: "chore: release ${{ steps.version-name.outputs.NEW_VERSION }}"
                    body: "Automatic PR for version release: ${{ steps.version-name.outputs.NEW_VERSION }}"
                    branch: ${{ github.ref }}
                    commit-message: "commit new version"











#            - name: Commit changes to GIT
#              run: |
#                git commit -a -m "chore: release v${{ steps.version-log.outputs.VERSION }}"
#                git push
#git tag -a ui-${{ steps.version-bump.outputs.NEW_VERSION }} -m "${{ steps.version-bump.outputs.GIT_PUSH_MSG }}"
#git push origin ui-${{ steps.version-bump.outputs.NEW_VERSION }}

#     echo "## PUBLISH ARGS: ${{ steps.lerna-args.outputs.PUBLISH }} :rocket:" >> $GITHUB_STEP_SUMMARY


# uses last commit details:
#"$(git log -n 1 --pretty=format:%an)"
#"$(git log -n 1 --pretty=format:%ae)"

#    - name: Cache node_modules
#          id: cache-node-modules
#          uses: actions/cache@v3
#          with:
#          path: node_modules
#          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#              ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-

